apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-web-first
  namespace: argo-cd-deployments
spec:
  destination:
    namespace: argo-cd-deployments
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/dummy-web-first
    repoURL: https://github.com/tyr13/argotest.git
    targetRevision: HEAD